"""initial

Revision ID: 2ef470fd580d
Revises: 4d6c6b051491
Create Date: 2023-06-24 11:37:42.943219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ef470fd580d'
down_revision = '4d6c6b051491'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
